[pytest]

addopts = 
    -v
    --alluredir=reports/allure-results

testpaths = tests

python_files = test_*.py
python_functions = test_*

markers =
    regression: running regression tests
    smoke: running smoke tests
    skip_ci: exclude tests in the CI pipeline